"""
main.py
=======
LLM-driven scientific data analysis application.

Multi-window architecture:
  1. ONE "Chat" window with the LLM (API key, connection test, log,
     prompt) — this is the core of the application; closing it exits
     the program.
  2. AS MANY "Data sheet" windows as desired ("+ New sheet" button).
     Importing a new file never overwrites an existing sheet: either
     import it into an already open window ("Import here"), or open a
     new window. Import/export always go through native file-selection
     windows, and are the ONLY way data ever touches disk — see
     import_into_window / export_data_window below.
  3. AS MANY "Chart" windows as desired ("+ New chart" button), to draw
     several curves/figures without overwriting previous ones.

Only one sheet and one chart are "active" at a time: these are the ones
the code generated by the LLM operates on by default (the `df`
variable, and the implicit `plt` figure). The user picks the active
window via the "Use for chat" button present in every data/chart
window.

The LLM only ever proposes Python code. This code always goes through
the security controller (security.py) before any execution
(executor.py). The generated code can NEVER read or write a file on
disk under any circumstance — see security.py and executor.py.

STATELESS CONVERSATION: each request sent to the LLM contains only the
system prompt (rebuilt fresh every time from the sheets/charts
currently open) and the user's current message — no prior turns are
included. The visible chat log below keeps the full transcript so the
user can scroll back or copy it, but nothing from earlier turns is
resent to the API.
"""

import os
import threading
import queue

import tkinter as tk
from tkinter import ttk, filedialog, messagebox, scrolledtext

import pandas as pd
import matplotlib.pyplot as plt

import llm_backend
import security
import executor
from windows import DataWindow, PlotWindow


APP_TITLE = "AI Assistant — Scientific Data Analysis"


class App:
    """
    Application controller. Keeps a hidden Tk root (self.root) that only
    exists to run the event loop; all visible windows (chat, data
    sheets, charts) are independent Toplevel windows, each freely
    movable and resizable.
    """

    def __init__(self):
        self.root = tk.Tk()
        self.root.withdraw()  # invisible root, only supports the mainloop

        self.result_queue = queue.Queue()   # thread(s) -> UI communication

        self.data_windows = []              # list[DataWindow]
        self.plot_windows = []              # list[PlotWindow]
        self.active_data_window = None
        self.active_plot_window = None

        self._build_chat_window()
        # An empty sheet and an empty chart are created at startup to
        # provide the initial "3 windows" look; the user can then open
        # as many more as desired.
        self.new_data_window()
        self.new_plot_window()
        self._position_initial_windows()

        self.root.after(150, self._poll_queue)
        self.chat_win.protocol("WM_DELETE_WINDOW", self._quit_app)

    def run(self):
        self.root.mainloop()

    def _quit_app(self):
        try:
            plt.close("all")
        except Exception:
            pass
        self.root.destroy()

    # ------------------------------------------------------------------
    # Convenience property: the active DataFrame (the one the LLM operates on)
    # ------------------------------------------------------------------
    @property
    def df(self):
        return self.active_data_window.df if self.active_data_window else None

    # ------------------------------------------------------------------
    # Initial positioning (purely cosmetic; everything remains movable
    # and resizable afterwards by the user)
    # ------------------------------------------------------------------
    def _position_initial_windows(self):
        sw = self.root.winfo_screenwidth()
        sh = self.root.winfo_screenheight()
        chat_w, chat_h = int(sw * 0.30), int(sh * 0.85)
        right_w, right_h = int(sw * 0.55), int(sh * 0.40)

        self.chat_win.geometry(f"{chat_w}x{chat_h}+40+40")
        if self.data_windows:
            self.data_windows[0].win.geometry(f"{right_w}x{right_h}+{chat_w + 80}+40")
        if self.plot_windows:
            self.plot_windows[0].win.geometry(f"{right_w}x{right_h}+{chat_w + 80}+{right_h + 90}")

    def _cascade_offset(self, n):
        """Small cascading offset so that new windows don't stack
        exactly on top of one another."""
        return 30 * (n % 10)

    # ==================================================================
    # Window 1: Chat
    # ==================================================================
    def _build_chat_window(self):
        self.chat_win = tk.Toplevel(self.root)
        self.chat_win.title("1. Chat with the LLM")
        self.chat_win.resizable(True, True)
        self.chat_win.minsize(420, 400)

        parent = self.chat_win
        parent.columnconfigure(0, weight=1)
        parent.rowconfigure(2, weight=1)

        # Provider (Groq only) + API key + model + connection test
        config_frame = ttk.LabelFrame(parent, text="LLM connection", padding=6)
        config_frame.grid(row=0, column=0, sticky="ew", padx=6, pady=(6, 4))

        self.provider_var = tk.StringVar(value="Groq")
        ttk.Label(config_frame, text="Provider:").grid(row=0, column=0, sticky="w")
        ttk.Label(config_frame, text="Groq", font=("", 9, "bold")).grid(
            row=0, column=1, sticky="w", padx=4, pady=2
        )

        ttk.Label(config_frame, text="API key:").grid(row=1, column=0, sticky="w")
        self.api_key_var = tk.StringVar(value=os.environ.get("GROQ_API_KEY", ""))
        ttk.Entry(config_frame, textvariable=self.api_key_var, show="*", width=30).grid(
            row=1, column=1, sticky="we", padx=4, pady=2
        )

        ttk.Label(config_frame, text="Model:").grid(row=2, column=0, sticky="w")
        self.model_var = tk.StringVar(value=llm_backend.DEFAULT_MODELS["Groq"])
        ttk.Entry(config_frame, textvariable=self.model_var, width=30).grid(
            row=2, column=1, sticky="we", padx=4, pady=2
        )
        config_frame.columnconfigure(1, weight=1)

        self.connection_status_var = tk.StringVar(value="Not tested")
        status_row = ttk.Frame(config_frame)
        status_row.grid(row=3, column=0, columnspan=2, sticky="ew", pady=(4, 0))
        ttk.Button(status_row, text="Test connection", command=self._on_test_connection).pack(side=tk.LEFT)
        self.connection_status_label = ttk.Label(
            status_row, textvariable=self.connection_status_var, foreground="#5e5c64"
        )
        self.connection_status_label.pack(side=tk.LEFT, padx=8)

        # Windows: creating new sheets/charts
        windows_frame = ttk.LabelFrame(parent, text="Windows", padding=6)
        windows_frame.grid(row=1, column=0, sticky="ew", padx=6, pady=(0, 4))
        ttk.Button(windows_frame, text="+ New sheet", command=lambda: self.new_data_window()).pack(
            side=tk.LEFT, padx=(0, 6)
        )
        ttk.Button(windows_frame, text="+ New chart", command=lambda: self.new_plot_window()).pack(
            side=tk.LEFT
        )

        # Chat log
        ttk.Label(parent, text="Log:").grid(row=2, column=0, sticky="nw", padx=6)
        log_frame = ttk.Frame(parent)
        log_frame.grid(row=2, column=0, sticky="nsew", padx=6, pady=(20, 6))
        parent.rowconfigure(2, weight=1)

        self.chat_log = scrolledtext.ScrolledText(log_frame, wrap=tk.WORD, state="disabled", font=("Consolas", 9))
        self.chat_log.pack(fill=tk.BOTH, expand=True)
        self._configure_log_tags()

        # Prompt input area
        prompt_frame = ttk.Frame(parent)
        prompt_frame.grid(row=3, column=0, sticky="ew", padx=6, pady=(0, 6))
        prompt_frame.columnconfigure(0, weight=1)

        self.prompt_text = tk.Text(prompt_frame, height=3, wrap=tk.WORD)
        self.prompt_text.grid(row=0, column=0, sticky="ew")
        self.prompt_text.bind("<Return>", self._on_enter_key)
        self.prompt_text.bind("<Shift-Return>", lambda e: None)  # allows a new line

        ttk.Button(prompt_frame, text="Send", command=self._on_send).grid(
            row=0, column=1, sticky="ns", padx=(6, 0)
        )

        self._log("system", "Welcome. Import a data file, then ask the LLM a question.")
        self._log("system", "This conversation has no memory: each request only tells the "
                             "LLM about the sheets/charts currently open, not about earlier "
                             "messages. The log below still keeps the full transcript so you "
                             "can scroll back or copy it.")
        self._log("system", "The LLM can never read or write a file on disk — import/export "
                             "only happens through the buttons in each sheet window.")
        self._log("system", "Tip: use 'Test connection' before chatting. Use "
                             "'+ New sheet' / '+ New chart' to open more windows "
                             "without overwriting the ones already open, and 'Use for chat' in a "
                             "window to make it active.")

    def _configure_log_tags(self):
        self.chat_log.tag_configure("user", foreground="#1a5fb4")
        self.chat_log.tag_configure("assistant", foreground="#2e2e2e")
        self.chat_log.tag_configure("system", foreground="#5e5c64")
        self.chat_log.tag_configure("denied", foreground="#c01c28", font=("Consolas", 9, "bold"))
        self.chat_log.tag_configure("confirm", foreground="#e5a50a", font=("Consolas", 9, "bold"))
        self.chat_log.tag_configure("allow", foreground="#26a269")
        self.chat_log.tag_configure("error", foreground="#c01c28")
        self.chat_log.tag_configure("code", foreground="#1c71d8", font=("Consolas", 9))

    def _log(self, tag, text):
        self.chat_log.configure(state="normal")
        self.chat_log.insert(tk.END, text.rstrip() + "\n\n", tag)
        self.chat_log.configure(state="disabled")
        self.chat_log.see(tk.END)

    # ==================================================================
    # "Data sheet" window management
    # ==================================================================
    def build_sheets_dict(self):
        """
        Builds a {unique_name: DataFrame} dictionary grouping ALL data
        sheets currently open, along with a name -> DataWindow lookup
        table so changes can be applied back after the LLM's code runs.
        Names are de-duplicated (e.g. 'data.csv', 'data.csv (2)') since
        several windows can share the same title.
        """
        sheets = {}
        name_to_window = {}
        used_names = set()
        for dw in self.data_windows:
            base = dw.title_str
            name = base
            i = 2
            while name in used_names:
                name = f"{base} ({i})"
                i += 1
            used_names.add(name)
            sheets[name] = dw.df if dw.df is not None else pd.DataFrame()
            name_to_window[name] = dw
        return sheets, name_to_window

    def _active_sheet_name(self, name_to_window):
        for name, dw in name_to_window.items():
            if dw is self.active_data_window:
                return name
        return None

    def new_data_window(self, df=None, title=None):
        dw = DataWindow(self, self.root, df=df, title=title)
        self.data_windows.append(dw)
        n = len(self.data_windows) - 1
        if n > 0:
            x = 100 + self._cascade_offset(n)
            y = 100 + self._cascade_offset(n)
            dw.win.geometry(f"700x420+{x}+{y}")
        self.set_active_data_window(dw)
        return dw

    def set_active_data_window(self, dw):
        self.active_data_window = dw
        for w in self.data_windows:
            w.set_active_visual(w is dw)
        if dw is not None:
            self._log("system", f"Active sheet for chat: '{dw.title_str}'.")

    def remove_data_window(self, dw):
        was_active = self.active_data_window is dw
        closed_name = dw.title_str
        if dw in self.data_windows:
            self.data_windows.remove(dw)
        if was_active:
            new_active = self.data_windows[-1] if self.data_windows else None
            self.set_active_data_window(new_active)
        self._log("system", f"Sheet '{closed_name}' closed. It is no longer available "
                             f"to the LLM — if a later request still refers to it by name, "
                             f"execution will be stopped with a clear message instead of "
                             f"an error, so you can rephrase.")

    def import_into_window(self, dw):
        """User-triggered import (the "Import here" button): always an
        interactive native file-selection window, never something the
        LLM's code can trigger."""
        path = filedialog.askopenfilename(
            title="Import a data file",
            filetypes=[("Supported files", "*.xlsx *.xls *.csv"),
                       ("Excel", "*.xlsx *.xls"), ("CSV", "*.csv")],
        )
        if not path:
            return
        try:
            if path.lower().endswith((".xlsx", ".xls")):
                df = pd.read_excel(path, engine="openpyxl") if path.lower().endswith(".xlsx") else pd.read_excel(path)
            else:
                df = pd.read_csv(path)
        except Exception as e:
            messagebox.showerror("Import error", f"Could not read the file:\n{e}")
            return

        dw.set_dataframe(df, title=os.path.basename(path))
        self._log("system", f"File imported into '{dw.title_str}': "
                             f"{df.shape[0]} rows, {df.shape[1]} columns.")
        if dw is not self.active_data_window:
            # importing does not automatically activate the window: the
            # user explicitly chooses via "Use for chat" if desired
            self._log("system", f"'{dw.title_str}' is not the active sheet. "
                                 f"Click 'Use for chat' in this window if needed.")

    def export_data_window(self, dw):
        """User-triggered export (the "Export .xlsx" button): always an
        interactive native "save as" window, never something the LLM's
        code can trigger."""
        if dw.df is None:
            messagebox.showwarning("Export", "No data to export in this window.")
            return
        path = filedialog.asksaveasfilename(
            title="Export data to a folder/file of your choice",
            defaultextension=".xlsx", filetypes=[("Excel", "*.xlsx")],
        )
        if not path:
            return
        try:
            dw.df.to_excel(path, index=False, engine="openpyxl")
            self._log("system", f"Data from '{dw.title_str}' exported to: {path}")
        except Exception as e:
            messagebox.showerror("Export error", str(e))

    # ==================================================================
    # "Chart" window management
    # ==================================================================
    def build_charts_dict(self):
        """Builds a {unique_name: Figure_or_None} dictionary grouping
        every chart window currently open, along with a name ->
        PlotWindow lookup table — the chart equivalent of
        build_sheets_dict()."""
        charts = {}
        name_to_window = {}
        used_names = set()
        for pw in self.plot_windows:
            base = pw.title_str
            name = base
            i = 2
            while name in used_names:
                name = f"{base} ({i})"
                i += 1
            used_names.add(name)
            charts[name] = pw.plot_fig
            name_to_window[name] = pw
        return charts, name_to_window

    def _active_chart_name(self, name_to_window):
        for name, pw in name_to_window.items():
            if pw is self.active_plot_window:
                return name
        return None

    def new_plot_window(self, title=None):
        pw = PlotWindow(self, self.root, title=title)
        self.plot_windows.append(pw)
        n = len(self.plot_windows) - 1
        if n > 0:
            x = 150 + self._cascade_offset(n)
            y = 150 + self._cascade_offset(n)
            pw.win.geometry(f"650x520+{x}+{y}")
        self.set_active_plot_window(pw)
        return pw

    def set_active_plot_window(self, pw):
        self.active_plot_window = pw
        for w in self.plot_windows:
            w.set_active_visual(w is pw)
        if pw is not None:
            self._log("system", f"Active chart for chat: '{pw.title_str}'.")

    def remove_plot_window(self, pw):
        was_active = self.active_plot_window is pw
        closed_name = pw.title_str
        if pw in self.plot_windows:
            self.plot_windows.remove(pw)
        if was_active:
            new_active = self.plot_windows[-1] if self.plot_windows else None
            self.set_active_plot_window(new_active)
        self._log("system", f"Chart '{closed_name}' closed. It is no longer available "
                             f"to the LLM — if a later request still refers to it by name, "
                             f"execution will be stopped with a clear message instead of "
                             f"an error, so you can rephrase.")

    # ==================================================================
    # LLM connection test
    # ==================================================================
    def _on_test_connection(self):
        provider = self.provider_var.get()
        api_key = self.api_key_var.get().strip()
        model = self.model_var.get().strip()

        self.connection_status_var.set("Testing...")
        self.connection_status_label.configure(foreground="#5e5c64")
        self._log("system", f"Testing connection to {provider} (model: {model})...")

        thread = threading.Thread(
            target=self._test_connection_worker, args=(provider, api_key, model), daemon=True
        )
        thread.start()

    def _test_connection_worker(self, provider, api_key, model):
        try:
            reply = llm_backend.test_connection(provider, api_key, model)
            self.result_queue.put(("test_ok", provider, model, reply))
        except Exception as e:
            self.result_queue.put(("test_error", provider, model, str(e)))

    # ==================================================================
    # Queue polling loop (UI thread)
    # ==================================================================
    def _poll_queue(self):
        try:
            while True:
                item = self.result_queue.get_nowait()
                kind = item[0]
                if kind == "llm_reply":
                    _, reply = item
                    self._handle_llm_reply(reply)
                elif kind == "llm_error":
                    _, err = item
                    self._log("error", f"Error calling the LLM:\n{err}")
                elif kind == "test_ok":
                    _, provider, model, reply = item
                    self.connection_status_var.set(f"\u2705 Connected ({provider} / {model})")
                    self.connection_status_label.configure(foreground="#26a269")
                    self._log("allow", f"LLM connected \u2705 — provider: {provider}, model: {model}\n"
                                        f"Test response received: {reply.strip()!r}")
                elif kind == "test_error":
                    _, provider, model, err = item
                    self.connection_status_var.set("\u274c Connection failed")
                    self.connection_status_label.configure(foreground="#c01c28")
                    self._log("error", f"LLM connection failed \u274c — provider: {provider}, "
                                        f"model: {model}\n{err}")
        except queue.Empty:
            pass
        self.root.after(150, self._poll_queue)

    # ==================================================================
    # Sending the prompt to the LLM
    # ==================================================================
    def _on_enter_key(self, event):
        if event.state & 0x0001:  # Shift held -> new line
            return
        self._on_send()
        return "break"

    def _on_send(self):
        prompt = self.prompt_text.get("1.0", tk.END).strip()
        if not prompt:
            return
        self.prompt_text.delete("1.0", tk.END)
        self._log("user", f"You: {prompt}")

        provider = self.provider_var.get()
        api_key = self.api_key_var.get().strip()
        model = self.model_var.get().strip()

        sheets, name_to_window = self.build_sheets_dict()
        active_sheet_name = self._active_sheet_name(name_to_window)
        charts, chart_name_to_window = self.build_charts_dict()
        active_chart_name = self._active_chart_name(chart_name_to_window)

        system_prompt = llm_backend.SYSTEM_PROMPT.replace(
            "{data_context}", llm_backend.build_data_context(sheets, active_sheet_name)
        ).replace(
            "{chart_context}", llm_backend.build_chart_context(charts, active_chart_name)
        )

        # STATELESS: only the (freshly rebuilt) system prompt and this
        # single user message are sent — no prior turns.
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ]

        self._log("system", f"Sending request to {provider} ({model})...")

        thread = threading.Thread(
            target=self._call_llm_worker, args=(provider, api_key, model, messages), daemon=True
        )
        thread.start()

    def _call_llm_worker(self, provider, api_key, model, messages):
        try:
            reply = llm_backend.call_llm(provider, api_key, model, messages)
            self.result_queue.put(("llm_reply", reply))
        except Exception as e:
            self.result_queue.put(("llm_error", str(e)))

    def _handle_llm_reply(self, reply):
        code = llm_backend.extract_code_block(reply)
        if code is None:
            self._log("assistant", f"LLM: {reply}")
            return

        self._log("assistant", "LLM proposes the following code:")
        self._log("code", code)
        self._run_through_security(code)

    # ==================================================================
    # Security controller + execution
    # ==================================================================
    def _run_through_security(self, code):
        # Pre-flight check: does the code reference a sheet or chart
        # name that is no longer open (e.g. mentioned in an earlier
        # turn, since closed by the user)? Caught here with a clear
        # message rather than letting it reach a raw KeyError during
        # execution.
        sheets_now, _ = self.build_sheets_dict()
        charts_now, _ = self.build_charts_dict()

        missing_sheets = security.find_read_dict_keys(code, "sheets") - set(sheets_now.keys())
        missing_charts = security.find_read_dict_keys(code, "charts") - set(charts_now.keys())
        if missing_sheets or missing_charts:
            msg_parts = []
            if missing_sheets:
                msg_parts.append("sheet(s) " + ", ".join(f"'{m}'" for m in sorted(missing_sheets)))
            if missing_charts:
                msg_parts.append("chart(s) " + ", ".join(f"'{m}'" for m in sorted(missing_charts)))
            self._log(
                "error",
                "The code refers to " + " and ".join(msg_parts) + " that are no longer open.\n"
                f"Currently open sheets: {', '.join(sheets_now.keys()) or '(none)'}.\n"
                f"Currently open charts: {', '.join(charts_now.keys()) or '(none)'}.\n"
                "This can happen when a window mentioned earlier has since been "
                "closed — remember this conversation has no memory between "
                "requests either. Ask again, specifying a window currently open."
            )
            return

        verdict = security.check_code(code)

        if verdict.status == "DENY":
            self._log("denied", "Denied — execution automatically refused.\nReason(s):\n"
                                 + verdict.reasons_text())
            return

        if verdict.status == "CONFIRM":
            details = verdict.reasons_text()
            self._log("confirm", "Confirmation required before execution.\nReason(s):\n" + details)
            approved = messagebox.askyesno(
                "Confirmation required",
                "The code proposed by the LLM contains one or more sensitive operations.\n\n"
                f"{details}\n\nDo you want to allow its execution?",
                icon="warning",
            )
            if not approved:
                self._log("system", "Execution cancelled by the user.")
                return
            self._log("allow", "Execution approved by the user.")
        else:  # ALLOW
            self._log("allow", "Allowed — no sensitive operation detected.")

        self._execute(code)

    def _execute(self, code):
        sheets, name_to_window = self.build_sheets_dict()
        active_sheet_name = self._active_sheet_name(name_to_window)
        charts, chart_name_to_window = self.build_charts_dict()

        new_df, new_sheets, chart_updates, implicit_fig, stdout_text, error = executor.execute_code(
            code, self.df, sheets=sheets, active_sheet_name=active_sheet_name, charts=charts,
        )

        if stdout_text:
            self._log("system", f"Output:\n{stdout_text}")

        if error:
            self._log("error", f"Error during execution:\n{error}")
            return

        # --- Apply modified / created sheets back --------------------
        for name, sheet_df in new_sheets.items():
            if not isinstance(sheet_df, pd.DataFrame):
                continue
            if name in name_to_window:
                dw = name_to_window[name]
                if dw.df is None or not sheet_df.equals(dw.df):
                    dw.set_dataframe(sheet_df)
                    marker = " (active sheet)" if dw is self.active_data_window else ""
                    self._log("system", f"Sheet '{name}' updated{marker}.")
            else:
                # A new key appeared in `sheets`: the LLM created a new
                # sheet -> automatically open a new window, WITHOUT
                # making it active (the user explicitly chooses via
                # "Use for chat" if they want to work on it next).
                new_win = DataWindow(self, self.root, df=sheet_df, title=name)
                self.data_windows.append(new_win)
                self._log("system", f"New sheet created by the LLM: '{name}' "
                                     f"({sheet_df.shape[0]} rows x {sheet_df.shape[1]} columns).")

        # --- Special case: no sheet was active, but the code still
        # produced a DataFrame via `df = ...` (not applied to `sheets`
        # since there was no active sheet name).
        if active_sheet_name is None and isinstance(new_df, pd.DataFrame) and new_df is not self.df:
            new_win = DataWindow(self, self.root, df=new_df, title="Result")
            self.data_windows.append(new_win)
            self.set_active_data_window(new_win)
            self._log("system", f"New sheet created by the LLM: '{new_win.title_str}'.")

        # --- Apply explicit chart[...] creations/replacements ---------
        for name, fig in chart_updates.items():
            if name in chart_name_to_window:
                pw = chart_name_to_window[name]
                pw.display_figure(fig)
            else:
                new_pw = PlotWindow(self, self.root, title=name)
                new_pw.display_figure(fig)
                self.plot_windows.append(new_pw)
                self._log("system", f"New chart created by the LLM: '{name}'.")

        # --- Implicit chart (plain plt.plot(...), `charts` untouched) -
        if implicit_fig is not None:
            target_plot = self.active_plot_window or self.new_plot_window()
            target_plot.display_figure(implicit_fig)


def main():
    app = App()
    app.run()


if __name__ == "__main__":
    main()
