"""
security.py
============
Security controller for the Python code generated by the LLM.

The code is NEVER executed as-is: it is first parsed into a syntax tree
(AST) and analyzed statically. Three possible verdicts:

  - "ALLOW"   : direct execution authorized
  - "CONFIRM" : requires explicit user confirmation
                (e.g. overwriting/creating a sheet or a chart)
  - "DENY"    : execution automatically refused, no confirmation
                possible (e.g. shell call, system command, network,
                environment/secret access, sandbox-escape primitives,
                ANY file read/write on disk)

NOTE: this analysis is a defense-in-depth heuristic, not a perfect
sandbox. It is combined with a restricted execution environment (see
executor.py) that limits the builtins and modules available at
execution time regardless. Static analysis and runtime confinement
are two independent layers; neither is assumed sufficient on its own.

Design note on file-system access: the LLM's generated code has NO way
to read or write a file on disk, period — not through open(), not
through pandas' read_csv/read_excel/to_csv/to_excel and friends. `os`,
`shutil` and `pathlib` are not importable, and executor.py does not
expose a working `open()` to the sandbox either. All import/export of
data goes exclusively through the manual, user-triggered "Import
here"/"Export .xlsx" buttons in the sheet windows (main.py), which are
trusted application code, not LLM-generated code, and are entirely
outside this module's scope.
"""

import ast

# ----------------------------------------------------------------------
# Modules whose import is entirely forbidden: low-level system access,
# shell, network, threading/process, dangerous introspection, and
# filesystem modules (no file access is permitted at all — see above).
# ----------------------------------------------------------------------
FORBIDDEN_MODULES = {
    "subprocess", "sys", "ctypes", "socket", "winreg", "ftplib",
    "telnetlib", "paramiko", "requests", "urllib", "urllib2",
    "http", "smtplib", "multiprocessing", "threading", "importlib",
    "pty", "pdb", "code", "commands", "webbrowser", "asyncio",
    "signal", "resource", "mmap", "fcntl",
    "os", "shutil", "pathlib", "glob", "tempfile", "io",
}

# Modules allowed for scientific data analysis. Deliberately excludes
# any module that grants direct filesystem, process, network or
# environment access — see FORBIDDEN_MODULES.
ALLOWED_MODULES = {
    "pandas", "pd", "numpy", "np", "matplotlib", "matplotlib.pyplot",
    "plt", "math", "statistics", "scipy", "seaborn", "sns",
    "datetime", "re", "json", "openpyxl",
    "itertools", "functools", "collections", "random",
}

# Functions/attributes whose call is immediately refused (DENY).
# Detected on the last segment of the dotted name (e.g. "os.system" -> "system").
DENY_CALL_KEYWORDS = {
    "system", "popen", "spawnl", "spawnle", "spawnlp", "spawnv",
    "spawnve", "spawnvp", "startfile", "exec", "eval", "compile",
    "__import__", "execfile", "fork", "kill", "killpg",
    "check_output", "check_call", "call", "run",
    "chmod", "chown", "setuid", "setgid",
    "connect", "socket", "bind", "listen", "sendto", "recvfrom",
    "getattr", "setattr", "delattr",
    # Reflective/introspection escapes not covered by attribute access
    # alone (e.g. `x.__getattribute__("__globals__")` is a Call, not a
    # bare Attribute, so DANGEROUS_ATTRIBUTES alone would miss it).
    "__getattribute__", "__getattr__", "__setattr__", "__delattr__",
    "globals", "locals", "vars",
    # Environment / secret access (API keys live in env vars).
    "environ", "getenv", "putenv", "unsetenv",
    # Any read or write of a file on disk — no exceptions. `open` and
    # every pandas file I/O function land here rather than in
    # CONFIRM_CALL_KEYWORDS: file import/export only ever happens
    # through the manual buttons in the sheet windows, never through
    # LLM-generated code.
    "open",
    "read_csv", "read_excel", "read_table", "read_json",
    "read_pickle", "read_parquet", "read_html", "read_xml", "read_sql",
    "to_csv", "to_excel", "to_pickle", "to_parquet", "to_json",
    "to_html", "to_xml", "to_sql", "save", "savefig",
}

# Sensitive calls that still require plain yes/no confirmation — none
# currently act on the filesystem (that's always DENY, see above);
# these are reserved for potentially destructive in-memory operations
# not already covered by the sheets[...]/charts[...] write checks.
CONFIRM_CALL_KEYWORDS = {
    "remove", "unlink", "rmdir", "removedirs", "rmtree",
    "move", "copyfile", "copytree",
}

# Dangerous reflective attributes (sandbox escape) when accessed
# directly, e.g. `x.__globals__`, `x.__class__.__bases__`.
DANGEROUS_ATTRIBUTES = {
    "__globals__", "__builtins__", "__subclasses__", "__bases__",
    "__mro__", "__class__", "__code__", "__closure__", "__dict__",
}

# Suspicious keywords inside string literals
# (heuristic against shell / disguised system commands).
SUSPICIOUS_STRING_KEYWORDS = [
    "powershell", "cmd.exe", "cmd /c", "/bin/sh", "/bin/bash",
    "bash -c", "wmic", "rm -rf", "del /f", "format c:", "shutdown",
    "reg add", "reg delete", "net user", "taskkill", "sudo ",
]


class SecurityVerdict:
    """Result of the security analysis of a piece of code."""

    def __init__(self, status, reasons):
        self.status = status      # "ALLOW" | "CONFIRM" | "DENY"
        self.reasons = reasons    # list[str]

    def __repr__(self):
        return f"<SecurityVerdict {self.status}: {self.reasons}>"

    def reasons_text(self):
        return "\n".join(f"- {r}" for r in self.reasons)


def _dotted_name(node):
    """Rebuilds a dotted name (e.g. os.path.remove) from an AST node."""
    parts = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
    return ".".join(reversed(parts))


def _is_dict_subscript(node, dict_name):
    """True if `node` has the form <dict_name>[...] or <dict_name>[...][...]...
    (nested access), at any depth, as long as the root of the chain is
    the name `dict_name` (e.g. "sheets" or "charts")."""
    if not isinstance(node, ast.Subscript):
        return False
    root = node
    while isinstance(root, (ast.Subscript, ast.Attribute)):
        root = root.value
    return isinstance(root, ast.Name) and root.id == dict_name


def _describe_dict_key(node, dict_name):
    """Describes the key targeted by <dict_name>['Key'] (including
    nested access, e.g. sheets['Name']['column'])."""
    cur = node
    while isinstance(cur, ast.Subscript) and not (
        isinstance(cur.value, ast.Name) and cur.value.id == dict_name
    ):
        cur = cur.value
    if isinstance(cur, ast.Subscript) and isinstance(cur.value, ast.Name) and cur.value.id == dict_name:
        key_node = cur.slice
        if isinstance(key_node, ast.Constant):
            return f"'{key_node.value}'"
    return "(dynamically computed name)"


def _iter_assignment_leaves(target):
    """Yields every leaf target of an assignment, recursing into tuple/list
    unpacking so that patterns like `_, sheets['X'] = a, b` or
    `[sheets['X'], y] = a, b` are not missed by the write checks."""
    if isinstance(target, (ast.Tuple, ast.List)):
        for elt in target.elts:
            yield from _iter_assignment_leaves(elt)
    else:
        yield target


def find_read_dict_keys(code: str, dict_name: str) -> set:
    """
    Returns the set of literal keys referenced for READING via
    <dict_name>['Key'] (a Subscript used in Load context) anywhere in
    `code` — e.g. `sheets['Sheet 1']['col']` or
    `pd.merge(sheets['A'], sheets['B'])` both count for dict_name='sheets'.

    Used by the application BEFORE execution to detect stale
    references to a sheet/chart window the user has since closed. Not
    a security concern by itself, so it deliberately lives outside
    check_code()/SecurityVerdict.
    """
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return set()

    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Subscript) and isinstance(node.ctx, ast.Load):
            if isinstance(node.value, ast.Name) and node.value.id == dict_name:
                key_node = node.slice
                if isinstance(key_node, ast.Constant) and isinstance(key_node.value, str):
                    names.add(key_node.value)
    return names


def check_code(code: str) -> SecurityVerdict:
    """Statically analyzes `code` and returns a SecurityVerdict."""
    deny_reasons = []
    confirm_reasons = []

    if not code or not code.strip():
        return SecurityVerdict("DENY", ["No code to analyze."])

    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return SecurityVerdict("DENY", [f"Invalid Python code (syntax error): {e}"])

    for node in ast.walk(tree):
        # --- Imports ---
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".")[0]
                if root in FORBIDDEN_MODULES:
                    deny_reasons.append(f"Forbidden module import: '{alias.name}'")
                elif root not in ALLOWED_MODULES:
                    deny_reasons.append(f"Unrecognized/unapproved module import: '{alias.name}'")

        elif isinstance(node, ast.ImportFrom):
            root = (node.module or "").split(".")[0]
            if root in FORBIDDEN_MODULES:
                deny_reasons.append(f"Forbidden module import: '{node.module}'")
            elif root not in ALLOWED_MODULES:
                deny_reasons.append(f"Unrecognized/unapproved module import: '{node.module}'")

        # --- Function calls ---
        elif isinstance(node, ast.Call):
            full_name = ""
            if isinstance(node.func, ast.Attribute):
                full_name = _dotted_name(node.func)
            elif isinstance(node.func, ast.Name):
                full_name = node.func.id

            last_part = full_name.split(".")[-1].lower() if full_name else ""

            if last_part in DENY_CALL_KEYWORDS:
                deny_reasons.append(f"Sensitive function call refused: '{full_name}(...)'")
            elif last_part in CONFIRM_CALL_KEYWORDS:
                confirm_reasons.append(f"Operation requiring confirmation: '{full_name}(...)'")

        # --- Suspicious string literals ---
        elif isinstance(node, ast.Constant) and isinstance(node.value, str):
            low = node.value.lower()
            for kw in SUSPICIOUS_STRING_KEYWORDS:
                if kw in low:
                    deny_reasons.append(f"Suspicious content detected in a string literal: '{kw}'")

        # --- Dangerous reflective attributes (direct attribute access) ---
        elif isinstance(node, ast.Attribute):
            if node.attr in DANGEROUS_ATTRIBUTES:
                deny_reasons.append(f"Dangerous reflective access refused: '.{node.attr}'")

        # --- Writing to another sheet/chart via the sheets/charts dict ---
        # Modifying `df` (resp. the implicit current chart) only touches
        # the active sheet/chart (already explicitly chosen by the user
        # via "Use for chat"), so it's ALLOW by default. But
        # `sheets['Name'] = ...` / `charts['Name'] = ...` can create a
        # new window or overwrite one the user isn't currently looking
        # at: this requires confirmation. Tuple/list unpacking targets
        # are flattened first so a nested write isn't missed.
        elif isinstance(node, ast.Assign):
            for raw_target in node.targets:
                for target in _iter_assignment_leaves(raw_target):
                    for dict_name, label in (("sheets", "sheet"), ("charts", "chart")):
                        if _is_dict_subscript(target, dict_name):
                            confirm_reasons.append(
                                f"Write to a {label} via {dict_name}[...]: "
                                f"{_describe_dict_key(target, dict_name)} (may create a "
                                f"new window or modify an existing one)"
                            )
                        elif isinstance(target, ast.Name) and target.id == dict_name:
                            confirm_reasons.append(
                                f"Full reassignment of the '{dict_name}' variable "
                                f"(replaces the code's known list of {label}s)"
                            )

        elif isinstance(node, ast.AugAssign):
            for dict_name, label in (("sheets", "sheet"), ("charts", "chart")):
                if _is_dict_subscript(node.target, dict_name):
                    confirm_reasons.append(
                        f"Modification of a {label} via {dict_name}[...] "
                        f"{_describe_dict_key(node.target, dict_name)} (operator +=, -=, etc.)"
                    )

    if deny_reasons:
        # de-duplicate while preserving order
        deny_reasons = list(dict.fromkeys(deny_reasons))
        return SecurityVerdict("DENY", deny_reasons)
    if confirm_reasons:
        confirm_reasons = list(dict.fromkeys(confirm_reasons))
        return SecurityVerdict("CONFIRM", confirm_reasons)
    return SecurityVerdict("ALLOW", [])
